### ISSUE TITLE
🚀 [feature]/44 프로필 조회 관련 기능 구현

### ISSUE THREAD

**Issue by koojun99** [Team-Shaka/Tree-Backend#44]
# 🤖 기능 개요

프로필 조회 관련 기능 구현
## ✅ Todo
- [x] 트리 가입(프로필) 때 프로필 이미지를 설정하지 않은 경우, 기본 프로필 이미지로 설정
- [x] 같은 트리에 속한 특정인의 프로필 조회 기능
- [x] 내 프로필 조회 기능
- [x] 브랜치 숫자 계산 및 조회 기능
