### ISSUE TITLE
📋 [docs]/47 - 전체 API 세부내용 문서화

### ISSUE THREAD

**Issue by koojun99** [Team-Shaka/Tree-Backend#47]
# 📋 문서화

현재까지 구현한 API들에 대한 세부 사항(Path, Param, 토큰 등) 문서화
## ✅ Todo
- [x] 전체 API에 대한 스웨거 세부 설정
- [x] 토큰 관련 스웨거 설정
- [x] 이미지 첨부 동작이 포함된 API에 대한 스웨거 최적화
